import { Portfolio, Trade, DashboardStats } from "@/types";

export const mockPortfolio: Portfolio = {
  id: "mock-1",
  name: "Binance Main",
  broker: "Binance",
  startingBalance: 10000,
  currency: "USDT",
  tradingStyle: "day_trading",
  createdAt: "2026-01-01T00:00:00Z",
};

export const mockTrades: Trade[] = [
  {
    id: "t1",
    portfolioId: "mock-1",
    pair: "BTC/USDT",
    market: "Crypto",
    direction: "long",
    outcome: "win",
    entryPrice: 62400,
    exitPrice: 64100,
    positionSize: 0.1,
    pnl: 170,
    pnlPercent: 2.72,
    dateTime: "2026-05-22T09:30:00Z",
    setupTag: "Breakout",
    emotionBefore: "confident",
    emotionAfter: "calm",
    mistakes: [],
    notes: "Clean breakout above resistance",
    createdAt: "2026-05-22T09:30:00Z",
  },
  {
    id: "t2",
    portfolioId: "mock-1",
    pair: "ETH/USDT",
    market: "Crypto",
    direction: "short",
    outcome: "loss",
    entryPrice: 3520,
    exitPrice: 3590,
    positionSize: 1,
    pnl: -70,
    pnlPercent: -1.99,
    dateTime: "2026-05-21T14:20:00Z",
    setupTag: "Trend Reversal",
    emotionBefore: "fomo",
    emotionAfter: "fearful",
    mistakes: ["fomo_entry"],
    notes: "Entered too early, trend still intact",
    lessonLearned: "Wait for confirmation before entry",
    createdAt: "2026-05-21T14:20:00Z",
  },
  {
    id: "t3",
    portfolioId: "mock-1",
    pair: "SOL/USDT",
    market: "Crypto",
    direction: "long",
    outcome: "win",
    entryPrice: 178,
    exitPrice: 192,
    positionSize: 10,
    pnl: 140,
    pnlPercent: 7.87,
    dateTime: "2026-05-20T11:00:00Z",
    setupTag: "Support Bounce",
    emotionBefore: "calm",
    emotionAfter: "disciplined",
    mistakes: [],
    notes: "Perfect bounce off key support",
    createdAt: "2026-05-20T11:00:00Z",
  },
  {
    id: "t4",
    portfolioId: "mock-1",
    pair: "BTC/USDT",
    market: "Crypto",
    direction: "long",
    outcome: "win",
    entryPrice: 61800,
    exitPrice: 62950,
    positionSize: 0.08,
    pnl: 92,
    pnlPercent: 1.86,
    dateTime: "2026-05-19T10:15:00Z",
    setupTag: "Breakout",
    emotionBefore: "confident",
    emotionAfter: "confident",
    mistakes: [],
    createdAt: "2026-05-19T10:15:00Z",
  },
  {
    id: "t5",
    portfolioId: "mock-1",
    pair: "AVAX/USDT",
    market: "Crypto",
    direction: "short",
    outcome: "loss",
    entryPrice: 38.5,
    exitPrice: 41.2,
    positionSize: 15,
    pnl: -40.5,
    pnlPercent: -7.01,
    dateTime: "2026-05-18T16:45:00Z",
    setupTag: "Distribution",
    emotionBefore: "fearful",
    emotionAfter: "revenge",
    mistakes: ["no_stop"],
    notes: "Stopped out. Held too long.",
    lessonLearned: "Always set stop loss before entering",
    createdAt: "2026-05-18T16:45:00Z",
  },
];

export const mockStats: DashboardStats = {
  totalPnl: 2480,
  totalPnlPercent: 24.8,
  winRate: 68,
  totalTrades: 34,
  streak: 3,
  streakType: "win",
  bestSetup: "Breakout",
  currentBalance: 12480,
};

export const mockPnlData = [
  { date: "May 1", pnl: 10000 },
  { date: "May 4", pnl: 10340 },
  { date: "May 7", pnl: 10180 },
  { date: "May 10", pnl: 10720 },
  { date: "May 13", pnl: 11050 },
  { date: "May 16", pnl: 10880 },
  { date: "May 19", pnl: 11420 },
  { date: "May 22", pnl: 12480 },
];
